### ISSUE TITLE
不支持gpu？

### ISSUE THREAD

**Issue by 2651084156** [mozillazg/pypinyin-g2pW#3]

**Comment by mozillazg** [comment]
支持的。安装对应环境的 [PyTorch](https://pytorch.org/get-started/locally/) 即可。

**Comment by 2651084156** [comment]
> 支持的。安装对应环境的 [PyTorch](https://pytorch.org/get-started/locally/) 即可。

那不对啊 我训练模型都是这个环境 确定调用了gpu 为什么他用的还是CPU啊而且还是单线程 然后这东西读取配置文件不指定编码 我改了一堆才正常

**Comment by 2651084156** [comment]
> > 支持的。安装对应环境的 [PyTorch](https://pytorch.org/get-started/locally/) 即可。
> 
> 那不对啊 我训练模型都是这个环境 确定是可以调用gpu的 为什么他用的还是CPU啊而且还是单线程 然后这东西读取配置文件不指定编码 我改了一堆才正常

**Comment by 2651084156** [comment]
emmm 淦修改点成回复了

**Comment by mozillazg** [comment]
> > 支持的。安装对应环境的 [PyTorch](https://pytorch.org/get-started/locally/) 即可。
> 
> 那不对啊 我训练模型都是这个环境 确定调用了gpu 为什么他用的还是CPU啊而且还是单线程 然后这东西读取配置文件不指定编码 我改了一堆才正常

@2651084156 嗯，这类 g2pW 相关问题麻烦去 https://github.com/GitYCC/g2pW/issues 这里咨询一下。
